### PR TITLE
Update source paths as recommended on StackOverflow

### PR DESCRIPTION
**Pull request by jonahgraham**
Here is what happens to the .cproject file with my recommended changes from http://stackoverflow.com/a/42402476/2796832

AFAICT the Fonts directory should be excluded because of duplicate symbols. I haven't tried to actually run your project.

### CODE REVIEW

**Comment by jonahgraham** [comment]
> but the requirements to build are a bit steep unless you happen to be developing for ST embedded processors.

...or happen to have found your question interesting enough. Your initial description made me worry there was a bug in CDT. Granted I think that if you explicitly right-click on a file and say compile it may be good to remind the user that the file is excluded from the current configuration. If you agree, please feel free to add a [feature request](https://bugs.eclipse.org/bugs/enter_bug.cgi?product=CDT) and let me know the bug number.

**Comment by HankB** [comment]
Thank you Jonah. I will file a feature request when I can get in. Right now I get "Either no products have been defined to enter bugs against or you have not been given access to any." but that may be because I am outside hours.

**Comment by HankB** [comment]
I have submitted the feature request: https://bugs.eclipse.org/bugs/show_bug.cgi?id=512700

Feel free to critique my submission. (Not something I do often.)

**Comment by jonahgraham** [comment]
Thanks, that is great.

**Pull request merged**
